services:
  - type: web
    name: regional-veiculos
    runtime: python
    pythonVersion: "3.13"
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py ensure_superuser"
    startCommand: "gunicorn regional_veiculos.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: regional-veiculos-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: regional_veiculos.settings_render
      - key: CLOUDINARY_URL
        value: "cloudinary://<your_api_key>:<your_api_secret>@dvuxxqmee"

databases:
  - name: regional-veiculos-db